name: .NET CI/CD
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build the project
        run: dotnet build --configuration Release
      - name: Test the project
        run: dotnet test
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.SERVER_HOST }}'
          username: '${{ secrets.SERVER_USERNAME }}'
          key: '${{ secrets.SERVER_SSH_KEY }}'
          script: |
            cd D:\Projects\IISConfiguration
            git pull origin master
            dotnet publish -c Release -o ./published
