name: CI/CD
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./OrderManagmentSystem/bin\Release\net7.0/
      - name: Deploy to local
        uses: actions/download-artifact@v2
        with:
          name: app
          path: ./OrderManagmentSystem/bin\Release\net7.0/
