name: CI/CD
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./OrderManagmentSystem/bin/Release/net7.0/
      - name: Create IISConfiguration directory if it doesn't exist
        run: 'New-Item -ItemType Directory -Force -Path D:/Projects/IISConfiguration'
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: 'D:/Projects/IISConfiguration/'
      - name: List files in IISConfiguration directory
        run: 'Get-ChildItem -Path D:/Projects/IISConfiguration/'
      - name: Copy artifact to Deployment
        run: >
          Get-ChildItem -Path D:/Projects/IISConfiguration/ -Filter "*.zip" |
          ForEach-Object {
            Copy-Item -Path $_.FullName -Destination D:/Projects/Deployment/
          }
